#pragma once

#ifdef IDC_STATIC
#undef IDC_STATIC
#endif
#define IDC_STATIC      (-1)

#define IDD_STAYAWAKE_DOCKPANEL         9000
#define IDC_STAYAWAKE_KEYS_ROSTER_BTN   9001
#define IDC_STAYAWAKE_INTERVAL_MIN      9002
#define IDC_STAYAWAKE_INTERVAL_MAX      9003
#define IDC_STAYAWAKE_SET_INTERVAL_BTN  9004
#define IDC_STAYAWAKE_LAST_EVENT        9005
#define IDC_STAYAWAKE_NEXT_EVENT        9006
#define IDC_STAYAWAKE_LAST_KEYCODE      9007
#define IDC_STAYAWAKE_PAUSE_RESUME_BTN  9011
#define IDC_STAYAWAKE_STEALTH_MODE      9012
#define IDC_STAYAWAKE_ABOUT_BUTTON      9013


#define IDD_SELECT_KEYCODES_DIALOG      9050
#define IDC_KEY_SCROLL_LOCK             9051
#define IDC_KEY_VOLUME_UP_DOWN          9052
#define IDC_KEY_UNASSIGNED_1            9053
#define IDC_KEY_UNASSIGNED_2            9054
#define IDC_KEY_UNASSIGNED_3            9055
#define IDC_KEY_UNASSIGNED_4            9056
#define IDC_KEY_UNASSIGNED_5            9057
#define IDC_KEY_UNASSIGNED_6            9058
#define IDC_KEY_UNASSIGNED_7            9059
#define IDC_KEY_UNASSIGNED_8            9060
#define IDC_KEY_UNASSIGNED_9            9061
#define IDC_KEY_UNASSIGNED_10           9062
#define IDC_KEY_SELECT_ALL_BTN          9071
#define IDC_KEY_SELECT_NONE_BTN         9072


#define IDB_STAYAWAKE_ABOUT_BITMAP      9091
#define IDI_STAYAWAKE_BTN_STD           9092
#define IDI_DOCK_DARK_MODE_ICON         9093
#define IDI_DOCK_LITE_MODE_ICON         9094


#define IDD_ABOUT_DIALOG                12000
#define IDC_ABOUT_NAME                  12001
#define IDC_ABOUT_VERSION               12002
#define IDC_ABOUT_ATTRIBUTION           12003
#define IDC_ABOUT_PROD_URL              12004
#define IDC_ABOUT_BUILD_TIME            12005
