#pragma once

#define IDD_STAYAWAKE_DOCKPANEL         9000
#define IDC_STAYAWAKE_KEY_LABEL         9001
#define IDC_STAYAWAKE_KEY_LIST          9002
#define IDC_STAYAWAKE_INTERVAL_LABEL    9003
#define IDC_STAYAWAKE_INTERVAL          9004
#define IDC_STAYAWAKE_SET_INTERVAL      9005
#define IDC_STAYAWAKE_LAST_TOGGLE       9006
#define IDC_STAYAWAKE_NEXT_TOGGLE       9007
#define IDC_STAYAWAKE_PAUSE_RESUME_BTN  9008
#define IDC_STAYAWAKE_STEALTH_MODE      9009
#define IDC_STAYAWAKE_ABOUT_BUTTON      9010

#define IDB_STAYAWAKE_ABOUT_BITMAP      9021
#define IDI_STAYAWAKE_BTN_STD           9022
#define IDI_DOCK_DARK_MODE_ICON         9023
#define IDI_DOCK_LITE_MODE_ICON         9024


#define IDD_ABOUT_DIALOG                12000
#define IDC_ABOUT_NAME                  12001
#define IDC_ABOUT_VERSION               12002
#define IDC_ABOUT_ATTRIBUTION           12003
#define IDC_ABOUT_PROD_URL              12004
#define IDC_ABOUT_BUILD_TIME            12005
